# Generated by Django 4.1.3 on 2023-01-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('phone_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=13)),
                ('details', models.TextField()),
                ('subject', models.CharField(max_length=225)),
                ('want', models.CharField(max_length=20)),
                ('meeting', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=60)),
                ('workmode', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=60)),
                ('documents', models.FileField(upload_to='')),
            ],
        ),
    ]
